apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
#allowVolumeExpansion: true
#mountOptions:
#  - debug
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - ap-south-1a
    - ap-south-1b
